### ISSUE TITLE
Pluralsight module2 config Helios -> DotNetty transformation

### ISSUE THREAD

**Issue by bacskaiz** [thelegendofando/Pluralsight#1]
Hi Simon!
Thank you for your Pluralsight course, I really liked it.
There are some changes in the Akka.NET library that cause your code not to be up to date.
In 2017 the Helios protocol was replaced with DotNetty, so the remote section in the config file should be modified to:
          
remote {
            dot-netty.tcp {
              transport-class = "Akka.Remote.Transport.DotNetty.TcpTransport, Akka.Remote"
              transport-protocol = tcp
              port = 0
              hostname = "127.0.0.1"
            }
          }
The demo is now works! :)

**Comment by ShinobiOtaku** [comment]
Hi @bacskaiz!

Thanks for your feedback, glad you enjoyed the course.

I'm going to keep this repo 'as is' so that it's matching the course, even if it is out of date. But thanks for bringing it to my attention.

Enjoy akka-ing.
